const OrderItem = require("../models/order-item.model");
const Comment = require("../models/comment.model");
const path = require("path");
const axios = require("axios");
const { v4: uuidv4 } = require("uuid");
const ftp = require("basic-ftp");
require("dotenv").config();
const { Op } = require("sequelize");
const sequelize = require("../../../config/database");
const sanitizeHtml = require("sanitize-html");
const { Readable } = require("stream");
const moment = require("moment");
const { uploadToFtp } = require("../../../middleware/upload");
const {
  sendNotification,
} = require("../../engagement/notification.controller"); // Import sendNotification
const { error } = require("console");
const {
  User,
  Order,
  Team,
  Customer,
  Quotation,
  Address,
  Product,
  InventoryHistory,
} = require("../../../models");
// 2. Log to inventory history (id auto-generated by hook)
const { v7: uuidv7 } = require("uuid"); // Make sure this is imported at the top!
const { pipeline } = require("stream");
const { promisify } = require("util");
const pipe = promisify(pipeline);
const PDFDocument = require("pdfkit");
const { ActivityLog } = require("../../../models");
const logActivity = require("../../../utils/activityLogger");

// ──────── HELPERS ────────
const VALID_STATUSES = [
  "PREPARING",
  "CHECKING",
  "INVOICE",
  "DISPATCHED",
  "DELIVERED",
  "PARTIALLY_DELIVERED",
  "CANCELED",
  "DRAFT",
  "ONHOLD",
  "CLOSED", // ← NEW
];
const VALID_PRIORITIES = ["high", "medium", "low"];
// ──────── HELPERS ──────── (add near the top of the controller file)
const canDispatch = (order) => {
  // Gate-pass is mandatory **only** when moving to DISPATCHED
  return order.gatePassLink !== null && order.gatePassLink.trim() !== "";
};
// Assume an admin user ID or system channel for notifications
const ADMIN_USER_ID = "2ef0f07a-a275-4fe1-832d-fe9a5d145f60"; // Replace with actual admin user ID or channel

function bufferToStream(buffer) {
  const stream = new Readable();
  stream.push(buffer);
  stream.push(null);
  return stream;
}

const uploadToCDN = async (file) => {
  const client = new ftp.Client();
  client.ftp.verbose = process.env.NODE_ENV === "development";

  try {
    await client.access({
      host: process.env.FTP_HOST,
      port: process.env.FTP_PORT || 21,
      user: process.env.FTP_USER,
      password: process.env.FTP_PASSWORD,
      secure: process.env.FTP_SECURE === "true",
    });

    const cwd = await client.pwd();
    const uploadDir = "/invoice_pdfs";
    await client.ensureDir(uploadDir);
    await client.cd(uploadDir);

    const ext = path.extname(file.originalname);
    const uniqueName = `${uuidv4()}-${Date.now()}${ext}`;
    await client.uploadFrom(bufferToStream(file.buffer), uniqueName);
    const fileUrl = `https://media.cmtradingco.com/invoice_pdfs/${uniqueName}`;
    return fileUrl;
  } catch (err) {
    throw new Error(`FTP upload failed: ${err.message}`);
  } finally {
    client.close();
  }
};

const sendErrorResponse = (res, status, message, details = null) => {
  const response = { message };
  if (details) response.details = details;
  return res.status(status).json(response);
};

const validateResource = async (resourceId, resourceType) => {
  const validResourceTypes = {
    Order: Order,
    Product: Product,
    Customer: Customer,
  };

  const Model = validResourceTypes[resourceType];
  if (!Model) {
    return { valid: false, error: `Invalid resourceType: ${resourceType}` };
  }

  const resource = await Model.findByPk(resourceId);
  if (!resource) {
    return { valid: false, error: `${resourceType} not found` };
  }

  return { valid: true, resource };
};

const validateCommentInput = ({
  resourceId,
  resourceType,
  userId,
  comment,
}) => {
  if (!resourceId || !resourceType || !userId || !comment?.trim()) {
    return {
      valid: false,
      error: "resourceId, resourceType, userId, and comment are required",
    };
  }

  const validResourceTypes = ["Order", "Product", "Customer"];
  if (!validResourceTypes.includes(resourceType)) {
    return { valid: false, error: `Invalid resourceType: ${resourceType}` };
  }

  return { valid: true };
};

const validateCommentFetchInput = ({ resourceId, resourceType }) => {
  if (!resourceId || !resourceType) {
    return {
      valid: false,
      error: "resourceId and resourceType are required",
    };
  }

  const validResourceTypes = ["Order", "Product", "Customer"];
  if (!validResourceTypes.includes(resourceType)) {
    return { valid: false, error: `Invalid resourceType: ${resourceType}` };
  }

  return { valid: true };
};

const fetchCommentsWithUsers = async (
  resourceId,
  resourceType,
  pageNum,
  limitNum,
) => {
  const comments = await Comment.find({ resourceId, resourceType })
    .sort({ createdAt: -1 })
    .skip((pageNum - 1) * limitNum)
    .limit(limitNum)
    .lean();

  const commentsWithUsers = await Promise.all(
    comments.map(async (comment) => {
      const user = await User.findOne({
        where: { userId: String(comment.userId) },
        attributes: ["userId", "username", "name"],
      });
      return {
        ...comment,
        user: user ? user.toJSON() : null,
      };
    }),
  );

  const totalCount = await Comment.countDocuments({ resourceId, resourceType });

  return { comments: commentsWithUsers, totalCount };
};

/**
 * Compute totals (GST, extra discount, final amount, amountPaid validation)
 * @returns {{gstValue, extraDiscountValue, subTotal, finalTotal}}
 */
function computeTotals({
  products = [],
  shipping = 0,
  gst = 0,
  extraDiscount = 0,
  extraDiscountType = "fixed",
  amountPaid = 0,
}) {
  // 1. Sub-total (price * qty after line-discount)
  const subTotal = products.reduce((sum, p) => sum + (p.total ?? 0), 0);

  // 2. Shipping
  const totalWithShipping = subTotal + Number(shipping);

  // 3. GST
  const gstValue = (totalWithShipping * Number(gst)) / 100;

  // 4. Extra discount
  let extraDiscountValue = 0;
  if (extraDiscount > 0) {
    extraDiscountValue =
      extraDiscountType === "percent"
        ? (totalWithShipping * Number(extraDiscount)) / 100
        : Number(extraDiscount);
  }

  // 5. **FINAL AMOUNT**
  const finalAmount = totalWithShipping + gstValue - extraDiscountValue;

  // // 6. amountPaid must not exceed final amount
  // if (Number(amountPaid) > finalAmount + 0.01) {
  //   throw new Error(
  //     `amountPaid (${amountPaid}) cannot exceed final amount (${finalAmount.toFixed(
  //       2
  //     )})`
  //   );
  // }

  return {
    subTotal,
    totalWithShipping,
    gstValue,
    extraDiscountValue,
    finalAmount, // <-- NEW
  };
}
// ─────────────────────────────────────────────────────────────
// Helper: Generate next daily sequential orderNo (DDMMYY101, etc.)
// ─────────────────────────────────────────────────────────────
async function generateDailyOrderNumber(t) {
  const todayStart = moment().startOf("day").toDate();
  const todayEnd = moment().endOf("day").toDate();
  const prefix = moment().format("DDMMYY"); // e.g. 150126

  let attempt = 0;
  const MAX_ATTEMPTS = 15;

  while (attempt < MAX_ATTEMPTS) {
    attempt++;

    // Find the highest sequence today
    const lastOrder = await Order.findOne({
      where: {
        orderNo: {
          [Op.like]: `${prefix}%`,
        },
        createdAt: {
          [Op.between]: [todayStart, todayEnd],
        },
      },
      attributes: ["orderNo"],
      order: [["orderNo", "DESC"]],
      limit: 1,
      transaction: t,
      lock: t.LOCK.UPDATE, // reduces race window
    });

    let nextSeq = 101;

    if (lastOrder) {
      const lastSeqStr = lastOrder.orderNo.slice(prefix.length);
      const parsed = parseInt(lastSeqStr, 10);
      if (!isNaN(parsed)) {
        nextSeq = parsed + 1;
      }
    }

    const candidate = `${prefix}${nextSeq}`;

    // Final collision check
    const conflict = await Order.findOne({
      where: { orderNo: candidate },
      transaction: t,
    });

    if (!conflict) {
      return candidate;
    }
  }

  throw new Error(
    `Failed to generate unique order number after ${MAX_ATTEMPTS} attempts`,
  );
}
/**
 * Reduce stock + log history (shared by create & update)
 */
async function reduceStockAndLog({
  productUpdates,
  createdBy,
  orderNo,
  customMessage,
  transaction,
}) {
  if (!transaction) throw new Error("Transaction is required");

  const username =
    (
      await User.findByPk(createdBy, {
        attributes: ["username"],
        transaction,
      })
    )?.username || "System";

  const autoMsg = `Stock removed by ${username} (Order #${orderNo})`;
  const msg = customMessage?.trim() ? `${customMessage} (${autoMsg})` : autoMsg;

  for (const upd of productUpdates) {
    const { productId, quantityToReduce, productRecord } = upd;

    if (quantityToReduce <= 0) continue; // safety

    const newQty = productRecord.quantity - quantityToReduce;

    // 1. Update product quantity
    await Product.update(
      { quantity: newQty },
      { where: { productId }, transaction },
    );

    // Inside the loop in reduceStockAndLog:
    await InventoryHistory.create(
      {
        id: uuidv7(), // ← Explicitly set the ID here!
        productId,
        change: -quantityToReduce,
        quantityAfter: newQty,
        action: "sale",
        orderNo: String(orderNo),
        userId: createdBy,
        message: msg,
      },
      { transaction },
    );

    // 3. Update status if needed
    let newStatus = "active";
    if (newQty === 0) {
      newStatus = "out_of_stock";
    } else if (
      productRecord.alert_quantity != null &&
      newQty <= productRecord.alert_quantity
    ) {
      newStatus = "low_stock";
    }

    if (newStatus !== productRecord.status) {
      await Product.update(
        { status: newStatus },
        { where: { productId }, transaction },
      );
    }
  }
}
/**
 * Restore stock when order is canceled / deleted
 */
async function restoreStock({ products, orderNo }) {
  if (!products?.length) return;

  for (const p of products) {
    const prod = await Product.findByPk(p.id || p.productId);
    if (!prod) continue;

    const qtyToAdd = p.quantity ?? 0;
    const newQty = prod.quantity + qtyToAdd;

    await Product.update(
      { quantity: newQty },
      { where: { productId: prod.productId } },
    );

    await InventoryHistory.create({
      productId: prod.productId,
      change: qtyToAdd,
      quantityAfter: newQty,
      action: "add-stock",
      orderNo,
      message: `Stock restored (order #${orderNo} cancelled/deleted)`,
    });
  }
}

module.exports = {
  OrderItem,
  Comment,
  path,
  axios,
  uuidv4,
  ftp,
  Op,
  sequelize,
  sanitizeHtml,
  Readable,
  moment,
  uploadToFtp,
  sendNotification,
  User,
  Order,
  Team,
  Customer,
  Quotation,
  Address,
  Product,
  InventoryHistory,
  uuidv7,
  PDFDocument,
  ActivityLog,
  logActivity,
  VALID_STATUSES,
  VALID_PRIORITIES,
  canDispatch,
  ADMIN_USER_ID,
  bufferToStream,
  uploadToCDN,
  sendErrorResponse,
  validateResource,
  validateCommentInput,
  validateCommentFetchInput,
  fetchCommentsWithUsers,
  computeTotals,
  generateDailyOrderNumber,
  reduceStockAndLog,
  restoreStock,
};
